# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [7]:
### [your code here]
print(np.__version__)
np.__config__

2.2.2


<module 'numpy.__config__' from '/usr/lib/python3.13/site-packages/numpy/__config__.py'>

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [12]:
### [your code here]
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [13]:
### [your code here]
print(a)

[[[0.23108001 0.89593346 0.21186426 0.66726483 0.58270797]
  [0.64274714 0.38370405 0.72304313 0.11072579 0.06703796]
  [0.87031398 0.90507311 0.84901769 0.09455088 0.58994994]]

 [[0.31903638 0.49065473 0.51457899 0.02374849 0.60294027]
  [0.4051701  0.62381361 0.36678238 0.40446836 0.00663427]
  [0.04975991 0.59451521 0.04065025 0.5604492  0.39077747]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [19]:
### [your code here]
b = np.random.randint(1 ,2, size=(5, 2, 3)) # tensor
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])


### 6. Print b.


In [20]:
### [your code here]
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [23]:
### [your code here]
a.size

30

In [24]:
b.size

30

a and b have the same size


### 8. Are you able to add a and b? Why or why not?


In [26]:
### [your code here]
a + b # cannot add a and b as their shapes are different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [27]:
b.shape

(5, 2, 3)

In [28]:
a.shape

(2, 3, 5)

In [36]:
a

array([[[0.23108001, 0.89593346, 0.21186426, 0.66726483, 0.58270797],
        [0.64274714, 0.38370405, 0.72304313, 0.11072579, 0.06703796],
        [0.87031398, 0.90507311, 0.84901769, 0.09455088, 0.58994994]],

       [[0.31903638, 0.49065473, 0.51457899, 0.02374849, 0.60294027],
        [0.4051701 , 0.62381361, 0.36678238, 0.40446836, 0.00663427],
        [0.04975991, 0.59451521, 0.04065025, 0.5604492 , 0.39077747]]])

In [37]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [42]:
### [your code here]
c = np.transpose(b, (1, 2, 0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [43]:
### [your code here]
d = a + c
d

array([[[1.23108001, 1.89593346, 1.21186426, 1.66726483, 1.58270797],
        [1.64274714, 1.38370405, 1.72304313, 1.11072579, 1.06703796],
        [1.87031398, 1.90507311, 1.84901769, 1.09455088, 1.58994994]],

       [[1.31903638, 1.49065473, 1.51457899, 1.02374849, 1.60294027],
        [1.4051701 , 1.62381361, 1.36678238, 1.40446836, 1.00663427],
        [1.04975991, 1.59451521, 1.04065025, 1.5604492 , 1.39077747]]])

In [44]:
a.shape

(2, 3, 5)

In [45]:
c.shape

(2, 3, 5)

a and c have same shapes. That's why it worked.


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [47]:
### [your code here]
print(a)

[[[0.23108001 0.89593346 0.21186426 0.66726483 0.58270797]
  [0.64274714 0.38370405 0.72304313 0.11072579 0.06703796]
  [0.87031398 0.90507311 0.84901769 0.09455088 0.58994994]]

 [[0.31903638 0.49065473 0.51457899 0.02374849 0.60294027]
  [0.4051701  0.62381361 0.36678238 0.40446836 0.00663427]
  [0.04975991 0.59451521 0.04065025 0.5604492  0.39077747]]]


In [48]:
print(d)

[[[1.23108001 1.89593346 1.21186426 1.66726483 1.58270797]
  [1.64274714 1.38370405 1.72304313 1.11072579 1.06703796]
  [1.87031398 1.90507311 1.84901769 1.09455088 1.58994994]]

 [[1.31903638 1.49065473 1.51457899 1.02374849 1.60294027]
  [1.4051701  1.62381361 1.36678238 1.40446836 1.00663427]
  [1.04975991 1.59451521 1.04065025 1.5604492  1.39077747]]]


In each element of a, 1 is added which is the common element of c


### 12. Multiply a and c. Assign the result to e.


In [49]:
### [your code here]
e = a * c
e

array([[[0.23108001, 0.89593346, 0.21186426, 0.66726483, 0.58270797],
        [0.64274714, 0.38370405, 0.72304313, 0.11072579, 0.06703796],
        [0.87031398, 0.90507311, 0.84901769, 0.09455088, 0.58994994]],

       [[0.31903638, 0.49065473, 0.51457899, 0.02374849, 0.60294027],
        [0.4051701 , 0.62381361, 0.36678238, 0.40446836, 0.00663427],
        [0.04975991, 0.59451521, 0.04065025, 0.5604492 , 0.39077747]]])



### 13. Does e equal to a? Why or why not?


In [52]:
### [your code here]
e == a # yes, e is equal to a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

c is a unit tensor. So if we multiply any other tensor with c, the value of the tensor will not change.



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [54]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [55]:
d_max

np.float64(1.905073108485153)

In [57]:
d_min

np.float64(1.006634269519917)

In [58]:
d_mean

np.float64(1.4406331266085952)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [61]:
### [your code here]
f = np.zeros(shape=d.shape)
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [62]:
d

array([[[1.23108001, 1.89593346, 1.21186426, 1.66726483, 1.58270797],
        [1.64274714, 1.38370405, 1.72304313, 1.11072579, 1.06703796],
        [1.87031398, 1.90507311, 1.84901769, 1.09455088, 1.58994994]],

       [[1.31903638, 1.49065473, 1.51457899, 1.02374849, 1.60294027],
        [1.4051701 , 1.62381361, 1.36678238, 1.40446836, 1.00663427],
        [1.04975991, 1.59451521, 1.04065025, 1.5604492 , 1.39077747]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [67]:
### [your code here]
x, y, z = f.shape
for i in range(x):
    for j in range(y):
        for k in range(z):
            # conditions here
            if d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75

f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  75.,  25.,  25.],
        [ 75., 100.,  75.,  25.,  75.]],

       [[ 25.,  75.,  75.,  25.,  75.],
        [ 25.,  75.,  25.,  25.,   0.],
        [ 25.,  75.,  25.,  75.,  25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [65]:
### [your code here]
d

array([[[1.23108001, 1.89593346, 1.21186426, 1.66726483, 1.58270797],
        [1.64274714, 1.38370405, 1.72304313, 1.11072579, 1.06703796],
        [1.87031398, 1.90507311, 1.84901769, 1.09455088, 1.58994994]],

       [[1.31903638, 1.49065473, 1.51457899, 1.02374849, 1.60294027],
        [1.4051701 , 1.62381361, 1.36678238, 1.40446836, 1.00663427],
        [1.04975991, 1.59451521, 1.04065025, 1.5604492 , 1.39077747]]])

In [66]:
f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  75.,  25.,  25.],
        [ 75., 100.,  75.,  25.,  75.]],

       [[ 25.,  75.,  75.,  25.,  75.],
        [ 25.,  75.,  25.,  25.,   0.],
        [ 25.,  75.,  25.,  75.,  25.]]])

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [88]:
### [your code here]
g = np.zeros(shape=d.shape)
g = g.astype(str)

x, y, z = d.shape
for i in range(x):
    for j in range(y):
        for k in range(z):
            # conditions here
            if d[i][j][k] == d_min:
                g[i][j][k] = "A"
            elif d[i][j][k] == d_max:
                g[i][j][k] = "E"
            elif d[i][j][k] == d_mean:
                g[i][j][k] = "C"
            elif d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g[i][j][k] = "B"
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                g[i][j][k] = "D"

In [89]:
g

array([[['B', 'D', 'B', 'D', 'D'],
        ['D', 'B', 'D', 'B', 'B'],
        ['D', 'E', 'D', 'B', 'D']],

       [['B', 'D', 'D', 'B', 'D'],
        ['B', 'D', 'B', 'B', 'A'],
        ['B', 'D', 'B', 'D', 'B']]], dtype='<U32')